### ISSUE TITLE
Delay/Lag/Sleep for requests

### ISSUE THREAD

**Issue by andreas-mausch** [sinedied/smoke#12]
Thanks for the project. I'm currently trying to use it as alternative to namshi/mockserver and like it much better. :)

The only thing missing for me is the `Response-Delay`, which is useful to see if loading animations, spinners etc. are shown correctly.

Do you think this can be added?

**Comment by sinedied** [comment]
There's currently no built-in option for that, but you can easily add it using [hooks](https://github.com/sinedied/smoke#middleware-hooks)

Something like this should do the trick:
```js
const delay = 1000; // in ms

function addDelay(req, res, next) {
  setTimeout(next, delay);
}

module.exports = {
  before: [addDelay],
  after: []
};
```

**Comment by andreas-mausch** [comment]
Thank you, this works for me.
