### ISSUE TITLE
Any plans on a new release?

### ISSUE THREAD

**Issue by Hypercubed** [sinedied/smoke#33]
Sorry to use issues for this request... but any plans on a release?

**Comment by sinedied** [comment]
Thanks for the reminder, sorry it's a bit complicated to find time for my OSS projects currently. I wanted to update the dependencies and add some test before doing a release.
Hopefully I can spend some time on it next week

**Comment by Hypercubed** [comment]
I understand.  Let me know if you need any help.  I have a few feature requests in mind... but don't want to burden you.
